unchained/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='info'),

]

unchained/unchained/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

unchained/music/models.py
# from __future__ import unicode_literals

from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

unchained/music/views.py
from django.views import generic
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/info.html'

unchained/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Musicfy</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'music:index' %}">Musicfy</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'music:index' %}">
                  <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                </a>
            </li>
            <li class="">
              <a href="#">
                  <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                </a>
              </li>
          </ul>

          <form class="navbar-form navbar-left" role="search" method="get" action="#">
              <div class='form-group'>
                  <input type="text" class="form-control" name="q" value="">
              </div>
              <button type="submit" class="btn btn-default">Search</button>
          </form>

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="#">
                  <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                </a>
            </li>
          </ul>

      </div>
  </nav>

{% block body %}
{% endblock %}
</body>
</html>

unchained/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Albums</h3>
        </div>
            {% for album in object_list %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:info' album.id %}">
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:info' album.id %}" class="btn btn-primary btn-sm" role="button">View Info</a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}


    </div>


</div>
{% endblock %}

unchained/music/templates/music/info.html
{% extends 'music/base.html' %}

{% block body %}

<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

<ul>
    {% for song in album.song_set.all %}
        <li>{{ song.song_title }} - {{ song.file_type }}</li>
    {% endfor %}
</ul>
{% endblock %}